// AUTO-GENERATED by tools/gate/device_harness_common.dart —— 不要手改。
// 每轮跑 gate 会用最新扫描到的 MattingEngineMixin 位置重新生成本文件。

import 'package:muzhao/core/matting/matting_engine.dart' as impl;

class GateMattingHarness extends Object with impl.MattingEngineMixin {
}
