// AUTO-GENERATED by tools/gate/device_harness_common.dart —— 不要手改。
// 每轮跑 gate 会用最新扫描到的 ComposeEngineMixin 位置重新生成本文件。
import 'dart:typed_data';

import 'package:muzhao/core/api.dart';
import 'package:muzhao/core/imaging/compose_engine.dart' as impl;

class GateComposeHarness extends Object with impl.ComposeEngineMixin {
  @override
  Future<void> warmUp() async {}
  @override
  Future<MattingResult> removeBackground(Uint8List imageBytes) => throw UnimplementedError('gate harness 占位，本轮评测不需要');
  @override
  Future<FaceInfo?> detectFace(Uint8List imageBytes) => throw UnimplementedError('gate harness 占位，本轮评测不需要');
  @override
  void dispose() {}
}
