// tools/gate/device_harness_common.dart
//
// G2A/G2B 都需要在真机/模拟器上跑实现类 agent 的 mixin（onnxruntime 用平台通道，
// 纯 `dart run` 摸不到）。这里提供一套通用机制：
//
// 1. 动态发现 ml-porting/imaging 交付的 mixin 文件（不硬编码文件名，避免和他们口头
//    约定文件路径——只认 CONTRACTS.md 锁定的类名 `MattingEngineMixin`/`ComposeEngineMixin`）。
// 2. 生成一个"胶水"harness 文件（放在 integration_test/_generated_*.dart，
//    每轮跑 gate 前重新生成，不手改），`class XxxHarness with 具体Mixin {}`，
//    给 integration_test 里的评测代码 import。
// 3. adb push/pull 帮手，用于把黄金集/数据集送上设备、把设备上产出的度量结果/合成图拉回来。
//
// **坑（已验证，见 docs/PITFALLS.md）**：`ComposeEngineMixin implements IdPhotoEngine`，
// 而 `MattingEngineMixin` 不带 `implements` 子句。如果 mixin 声明了
// `implements IdPhotoEngine`，`class X with 该Mixin {}` 必须把 IdPhotoEngine 的全部
// 5 个方法都补全才能编译——即使我们只关心其中一个。所以 generateHarnessFile 会检测
// 这个 `implements` 子句，需要的话补齐占位桩（throw UnimplementedError），
// **但绝不能给 mixin 已经真正实现的那个方法也生成桩**——类体里直接声明的方法会
// 盖过 mixin 里的同名方法（Dart 的 linearization 规则），桩会静默替换掉真实实现，
// 测试看起来能跑但测的是空壳。所以 `providedMethods` 参数必须精确。
//
// 势力范围：gatekeeper。

import 'dart:io';

import 'gate_common.dart';

class MixinLocation {
  final String importPath; // 相对 lib/，如 'core/matting/matting_engine.dart'
  final bool implementsIdPhotoEngine;
  const MixinLocation(this.importPath, this.implementsIdPhotoEngine);
}

/// 在 [libSubDir]（如 'lib/core/matting'）下递归找 `mixin $mixinName` 声明所在文件。
/// 找不到返回 null —— 调用方必须显式 FAIL/说明"待交付"，不许当成通过。
Future<MixinLocation?> findMixinImportPath(String libSubDir, String mixinName) async {
  final dir = Directory(libSubDir);
  if (!await dir.exists()) return null;
  final declPattern = RegExp(r'mixin\s+' + mixinName + r'\b([^{]*)\{');
  await for (final entity in dir.list(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    final content = await entity.readAsString();
    final m = declPattern.firstMatch(content);
    if (m != null) {
      final clause = m.group(1) ?? '';
      final implementsEngine = clause.contains('IdPhotoEngine');
      final backslash = String.fromCharCode(92);
      final normalized = entity.path.replaceAll(backslash, '/');
      final idx = normalized.indexOf('lib/');
      if (idx == -1) return null;
      return MixinLocation(normalized.substring(idx + 4), implementsEngine);
    }
  }
  return null;
}

/// IdPhotoEngine 的 5 个方法，除了调用方指定的 [providedMethods] 之外全部生成占位桩
/// （仅当 [location].implementsIdPhotoEngine 为 true 时才需要，否则 mixin 本身
/// 没有声明实现整个接口，class 不需要补全）。
Future<void> generateHarnessFile({
  required String outPath,
  required MixinLocation location,
  required String className,
  required String mixinName,
  required Set<String> providedMethods, // 子集 of {warmUp, removeBackground, detectFace, compose, dispose}
}) async {
  final stubs = StringBuffer();
  var needsRect = false;
  if (location.implementsIdPhotoEngine) {
    if (!providedMethods.contains('warmUp')) {
      stubs.writeln('  @override');
      stubs.writeln('  Future<void> warmUp() async {}');
    }
    if (!providedMethods.contains('removeBackground')) {
      stubs.writeln('  @override');
      stubs.writeln('  Future<MattingResult> removeBackground(Uint8List imageBytes) => '
          "throw UnimplementedError('gate harness 占位，本轮评测不需要');");
    }
    if (!providedMethods.contains('detectFace')) {
      stubs.writeln('  @override');
      stubs.writeln('  Future<FaceInfo?> detectFace(Uint8List imageBytes) => '
          "throw UnimplementedError('gate harness 占位，本轮评测不需要');");
    }
    if (!providedMethods.contains('compose')) {
      needsRect = true;
      stubs.writeln('  @override');
      stubs.writeln('  Future<Candidate> compose({required MattingResult matting, '
          'required PhotoSpec spec, required BackgroundStyle style, FaceInfo? face, '
          "Rect? cropOverride}) => throw UnimplementedError('gate harness 占位，本轮评测不需要');");
    }
    if (!providedMethods.contains('dispose')) {
      stubs.writeln('  @override');
      stubs.writeln('  void dispose() {}');
    }
  }

  final needsApiImport = location.implementsIdPhotoEngine;
  final content = '''
// AUTO-GENERATED by tools/gate/device_harness_common.dart —— 不要手改。
// 每轮跑 gate 会用最新扫描到的 $mixinName 位置重新生成本文件。
${needsApiImport ? "import 'dart:typed_data';\n${needsRect ? "import 'dart:ui' show Rect;\n" : ''}\nimport 'package:muzhao/core/api.dart';" : ''}
import 'package:muzhao/${location.importPath}' as impl;

class $className extends Object with impl.$mixinName {
$stubs}
''';
  final file = File(outPath);
  await file.parent.create(recursive: true);
  await file.writeAsString(content);
}

/// adb push 一个文件或目录到设备。
/// 建好设备端评测目录并放开权限（777）。
///
/// **坑（已验证，见 docs/PITFALLS.md）**：`/sdcard/...` 受 Android 10+ scoped storage
/// 管辖，`adb push` 建的文件属主是 shell 的 `media_rw` 组，App 自己的沙箱 UID 不在这个组
/// 里，读会直接 EACCES（errno=13），跟模型/代码对不对完全无关。改用
/// `/data/local/tmp/`——这是真实 ext4 路径，不走 scoped storage 的 FUSE 模拟层。
/// `adb push` 建的文件默认是 world-readable（rw-rw-rw-），子目录 world-traversable
/// （rwxrwxr-x），App 读没问题；但顶层目录本身默认只有 shell 能写，App 要在这里面
/// 写结果 JSON，必须显式 chmod 777 顶层目录（子目录/文件不需要，只有 App **新建**
/// 文件的那一层父目录需要写权限）。
Future<RunResult> prepareDeviceGateDir(String deviceId, String remoteDir) async {
  return runProcess(
    'adb',
    ['-s', deviceId, 'shell', 'mkdir -p $remoteDir && chmod 777 $remoteDir'],
    timeout: const Duration(seconds: 20),
  );
}

Future<RunResult> adbPush(String deviceId, String localPath, String remotePath) {
  return runProcess('adb', ['-s', deviceId, 'push', localPath, remotePath],
      timeout: const Duration(minutes: 5));
}

/// adb pull 一个文件或目录回主机。
Future<RunResult> adbPull(String deviceId, String remotePath, String localPath) {
  return runProcess('adb', ['-s', deviceId, 'pull', remotePath, localPath],
      timeout: const Duration(minutes: 5));
}

/// 在设备上跑一个 integration_test 目标文件（`flutter test` 直接支持，无需 flutter drive）。
Future<RunResult> runIntegrationTestOnDevice(
  String targetPath,
  String deviceId, {
  Duration timeout = const Duration(minutes: 10),
}) {
  return runProcess(
    'flutter',
    ['test', targetPath, '-d', deviceId],
    timeout: timeout,
  );
}

/// 设备上供测试读写的公共临时目录（推送黄金集/数据集、拉回结果都用这个）。
const String kDeviceGateTmpDir = '/data/local/tmp/muzhao_gate_tmp';
